---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppppoot
  labels:
    app: ppppoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppppoot
  template:
    metadata:
      labels:
        app: ppppoot
    spec:
      containers:
        - name: ppppoot
          image: docker.io/phengbunath/ppppoot:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
